name: Semgrep
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to run Semgrep against'
        required: false
        default: 'main'
  push:
    branches:
      - master
      - main
      - develop
  pull_request: {}

  # If you want to schedule Semgrep runs, then put some random time
  # to avoid cross-running in multiple repositories at the same time

  #schedule:
    #- cron: '45 17 * * 3'

jobs:
  semgrep:
    name: semgrep/ci
    permissions:
      contents: read
      pull-requests: write
      issues: write
    uses: ignitetech-group/semgrep/.github/workflows/semgrep-reusable.yml@v1
    secrets: inherit
    with:
      target_branch: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target_branch || github.ref_name }}
      is_pr: ${{ github.event_name == 'pull_request' }}
      pr_number: ${{ github.event.pull_request.number || '' }}
